apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: event-booking
  labels:
    app: elasticsearch
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/part-of: event-booking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    app: elasticsearch
