apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: event-booking
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: event-booking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: backend
