apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: event-booking
  labels:
    app: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: event-booking
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
