# =========================================================
# LOCAL DEVELOPMENT PROFILE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3307/event_booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=booking_user
spring.datasource.password=change_me_strong_password

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.elasticsearch.uris=http://[::1]:9200

# Local development JWT secret
app.jwt.secret=local-dev-jwt-secret-do-not-use-in-production-12345678901234567890

spring.devtools.restart.enabled=true

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG