spring.jpa.hibernate.ddl-auto=validate

logging.level.com.booking=INFO
logging.level.org.hibernate.SQL=ERROR

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
