apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: event-booking
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: event-booking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
